# frozen_string_literal: true

namespace :'plugin:archives' do
  desc 'Install dependencies'
  task :install do
    command = <<~SHELL
      cd #{__dir__} && npm install
    SHELL
    fail unless system(command)
  end

  desc 'Build JavaScript'
  task build_js: [:install] do
    command = <<~SHELL
                cd #{__dir__} && env NODE_ENV=production ./node_modules/.bin/webpack --config webpack.production.config.js
              SHELL
    fail unless system(command)
  end
end
