# frozen_string_literal: true

namespace :'theme:portalshit' do
  desc 'Install dependencies'
  task :install do
    command = <<~SHELL
      export PATH="$HOME/.nodenv/bin:$PATH"
      eval "$(nodenv init -)"
      cd #{__dir__} && $HOME/.nodenv/shims/npm install
    SHELL
    fail unless system(command)
  end

  desc 'Build JavaScript'
  task build_js: [:install] do
    command = <<~SHELL
      export PATH="$HOME/.nodenv/bin:$PATH"
      eval "$(nodenv init -)"
      cd #{__dir__} && npx webpack --config webpack.config.js
    SHELL
    fail unless system(command)
  end
end
