inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 2.5
  Exclude:
    - lokka.gemspec
    - db/seeds.rb
    - vendor/bundle/**/*
    - config/**/*
    - Capfile

Style/Documentation:
  Enabled: false

Naming/MethodName:
  Exclude:
    - lib/lokka/models/**/*

Style/StringLiterals:
  EnforcedStyle: single_quotes
  SupportedStyles:
    - single_quotes
    - double_quotes

Layout/EmptyLineAfterGuardClause:
  Enabled: false

Layout/AlignParameters:
  EnforcedStyle: with_fixed_indentation
  SupportedStyles:
    - with_first_parameter
    - with_fixed_indentation

Layout/AlignArguments:
  EnforcedStyle: with_fixed_indentation

Layout/AlignHash:
  EnforcedHashRocketStyle: table

Layout/DotPosition:
  EnforcedStyle: trailing

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented_relative_to_receiver

Layout/MultilineOperationIndentation:
  EnforcedStyle: indented

Layout/SpaceInsideBlockBraces:
  EnforcedStyleForEmptyBraces: space
  SpaceBeforeBlockParameters: false

Lint/AmbiguousBlockAssociation:
  Exclude:
    - spec/**/*

Lint/UselessAssignment:
  Exclude:
    - lib/lokka/helpers/helpers.rb
    - public/theme/Farikal/config.rb

Metrics/BlockLength:
  ExcludedMethods:
    - refine
  Exclude:
    - spec/**/*
    - lib/lokka/before.rb
    - lib/lokka/app.rb
    - lib/lokka/importer.rb
    - '**/*_spec.rb'
    - lib/tasks/similar_entries.rake

Metrics/LineLength:
  Exclude:
    - Gemfile
    - public/**/*
  IgnoredPatterns:
    - '%r'
    - '%q'
    - '%Q'
    - '/\/.+\//'

Metrics/PerceivedComplexity:
  Exclude:
    - lib/lokka/before.rb
    - lib/lokka/importer.rb
    - public/plugin/**/*
