services:
  db:
    image: mysql:9
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
      - data-volume:/var/lib/mysql
  app:
    image: morygonzalez/portalshit
    platform: linux/amd64
    environment:
      DB_HOST: db
      SESSION_SECRET: 'secret'
      OLD_SESSION_SECRET: 'old_secret'
    build: .
    command: ['bundle', 'exec', 'puma']
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - db
volumes:
  data-volume:
