version: '3.1'
services:
  db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
      - data-volume:/var/lib/mysql
  app:
    image: morygonzalez/portalshit
    secrets:
      - newrelic_config
    environment:
      DB_HOST: db
    build: .
    command: bundle exec puma
    volumes:
      - .:/app
      - bundle:/user/local/bundle
    ports:
      - "3000:3000"
    depends_on:
      - db
volumes:
  data-volume:
  bundle:
secrets:
  newrelic_config:
    file: config/newrelic.yml
