version: 2
jobs:
  build:
    working_directory: ~/app
    docker:
      - image: morygonzalez/portalshit:latest
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD
        environment:
          RAILS_ENV: test
    steps:
      - checkout
      - run:
          name: Bundle install
          command: |
            bundle config set path /usr/local/bundle
            bundle config set without 'mysql postgresql'
            bundle install -j1
      - run:
          name: Database set up
          command: |
            : > db/test.sqlite3
            RACK_ENV=test bundle exec rake db:migrate
      - run:
          name: Run rspec
          command: |
            RACK_ENV=test bundle exec rspec --format progress
      - run:
          name: Deploy to production
          command: |
            if [ ${CIRCLE_BRANCH} = 'portalshit' ]; then
              bundle exec cap production deploy
            fi
