require 'json'
require_relative 'lib/lokka/photo_gallery/metadata_generator'
require_relative 'lib/lokka/photo_gallery/renderer'

namespace :photo_gallery do
  desc '画像からmetadata.jsonを生成'
  task :generate_metadata, [:folder, :do_upload] do |_, args|
    folder = args[:folder]
    do_upload = ActiveModel::Type::Boolean.new.cast(args[:do_upload])
    Lokka::PhotoGallery::MetadataGenerator.new(folder, do_upload: do_upload).generate
  end

  desc 'metadata.jsonからHTMLを生成'
  task :generate_html, [:folder] do |_, args|
    folder = args[:folder]
    metadata_file = File.join(folder, 'metadata.json')

    unless File.exist?(metadata_file)
      abort "#{metadata_file} が存在しません。先に rake photo_gallery:generate_metadata を実行してください。"
    end

    images = JSON.parse(File.read(metadata_file), symbolize_names: true).sort_by { |item| item[:taken_at] }
    renderer = Lokka::PhotoGallery::Renderer.new(images)
    puts renderer.render
  end
end
