garmin:
  "4312": "Garmin epix Pro (Gen 2) 42mm"
  "4313": "Garmin epix Pro (Gen 2) 47mm"
  "4314": "Garmin epix Pro (Gen 2) 51mm"
"1":
  "4312": "Garmin epix Pro (Gen 2) 42mm"
  "4313": "Garmin epix Pro (Gen 2) 47mm"
  "4314": "Garmin epix Pro (Gen 2) 51mm"
"294":
  "804": "COROS Pace 3"
